### ISSUE TITLE
Please update description/metadata for this repo

### ISSUE THREAD

**Issue by apsamuel** [conda-forge/packer-feedstock#6]
Issue:

The details and metadata for this repository are in context to terraform, yet this repository is for packer. 

This is an example of the data being incorrectly displayed for this package as a result. https://anaconda.org/conda-forge/packer
<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by mariusvniekerk** [comment]
Done in #8
